"$schema" = "./node_modules/wrangler/config-schema.json"
name = "Savi"
main = "src/worker.js"
# Set this to today's date
compatibility_date = "2026-04-21"
workers_dev = false

[route]
pattern = "savi.st3.dolphinlabs.ie/*"
zone_name = "savi.st3.dolphinlabs.ie"

[[kv_namespaces]]
binding = "KV"
id = "32efb4e5fbd34fa0abe79096cfcd6358"

[env.staging]
name = "my-worker-staging"

  [env.staging.route]
  pattern = "savi.st3.dolphinlabs.ie/*"
  zone_name = "savi.st3.dolphinlabs.ie"

  [[env.staging.kv_namespaces]]
  binding = "KV"
  id = "32efb4e5fbd34fa0abe79096cfcd6358"